version: "3"
services:
  jellyfin:
    container_name: jellyfin
    image: jellyfin/jellyfin
    restart: unless-stopped
    networks:
      - gateway-proxy
    ports:
      - 8096:8096
    volumes:
      - ./volumes/jellyfin/config:/config
      - ./volumes/jellyfin/cache:/cache
      - "${SERIES_DIR}:/media/series"
      - "${MOVIES_DIR}:/media/movies"
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.${DOMAIN}`)"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"
  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:preview
    restart: unless-stopped
    ports:
      - 8989:8989
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      - gateway-proxy
    volumes:
      - ./volumes/sonarr:/config
      - ${DL_DIR}/completed:/downloads/completed
      - ${SERIES_DIR}:/series
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - jackett
      - deluge
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sonarr.rule=Host(`series.${DOMAIN}`)"
      - "traefik.http.services.sonarr.loadbalancer.server.port=8989"
  radarr:
    container_name: radarr
    image: linuxserver/radarr
    restart: unless-stopped
    networks:
      - gateway-proxy
    ports:
      - 7878:7878
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./volumes/radarr:/config
      - ${DL_DIR}/completed:/downloads/completed
      - ${MOVIES_DIR}:/movies
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - jackett
      - deluge
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.radarr.rule=Host(`movies.${DOMAIN}`)"
      - "traefik.http.services.radarr.loadbalancer.server.port=7878"
  deluge:
    image: linuxserver/deluge
    container_name: deluge
    networks:
      - gateway-proxy
    ports:
      - 8118:8118
      - 58846:58846
      - 58946:58946
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Europe/London
    volumes:
      - ${DL_DIR}:/downloads
      - ./volumes/deluge:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.deluge.rule=Host(`torrents.${DOMAIN}`)"
      - "traefik.http.services.deluge.loadbalancer.server.port=8112"
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    restart: unless-stopped
    networks:
      - gateway-proxy
    ports:
      - 9117:9117
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ./volumes/jackett:/config
      - ${DL_DIR}/completed:/downloads
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jackett.rule=Host(`trackers.${DOMAIN}`)"
      - "traefik.http.services.jackett.loadbalancer.server.port=9117"
  heimdall:
    image: linuxserver/heimdall
    container_name: heimdall
    networks:
      - gateway-proxy
    ports:
      - 8888:80
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Europe/London
    volumes:
      - ./volumes/heimdall:/config
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.heimdall.rule=Host(`index.${DOMAIN}`)"
      - "traefik.http.services.heimdall.loadbalancer.server.port=8888"

networks:
  gateway-proxy:
    external: true
